### ISSUE TITLE
ex_doc escript missing from latest Hex release

### ISSUE THREAD

**Issue by weiss** [starbelly/rebar3_ex_doc#15]
It seems the 0.2.7 release on Hex.pm is missing the `priv` directory, I run into `_build/default/plugins/rebar3_ex_doc/priv/ex_doc: not found`.  Using `{plugins, [{rebar3_ex_doc, "0.2.6"}]}` works around this issue.

**Comment by filmor** [comment]
This is fixed in version [0.2.8](https://hex.pm/packages/rebar3_ex_doc).

**Comment by weiss** [comment]
Indeed, thanks!
