### ISSUE TITLE
Make specifying --package optional

### ISSUE THREAD

**Issue by weiss** [starbelly/rebar3_ex_doc#16]
I use ExDoc for documenting a "top-level" application (as opposed to a library to be used by others) which isn't published to Hex. Therefore, it would be nice if there was a way to avoid specifying [the `--package` argument][1], which adds links to Hex.pm.

[1]: https://github.com/starbelly/rebar3_ex_doc/blob/main/src/rebar3_ex_doc.erl#L197-L198

**Comment by starbelly** [comment]
That makes since to me. What we could do is move the responsibility of setting `--package` from this plugin to rebar3_hex.

**Comment by starbelly** [comment]
This is old, but not forgotten. I think what would be better is add an option for this plugin `{no_package, true}` or something similar, then rebar3_hex doesn't have concern itself with particulars of this plugin. 

Thoughts?

**Comment by weiss** [comment]
> I think what would be better is add an option for this plugin {no_package, true} or something similar

Sounds good to me :+1:
