### ISSUE TITLE
Don't assume 'v' prefix for Git tags

### ISSUE THREAD

**Issue by weiss** [starbelly/rebar3_ex_doc#18]
The plugin currently [hard-codes][1] the assumption that Git tags have a `v` prefix, so source references are broken for tags [without prefix][2].  I guess it might be nice to make this configurable.

[1]: https://github.com/starbelly/rebar3_ex_doc/blob/v0.2.7/src/rebar3_ex_doc.erl#L190
[2]: https://stackoverflow.com/a/37781173

**Comment by starbelly** [comment]
That's fair. There was a request for this in rebar3_hex as well.

**Comment by arjan** [comment]
:+1: would be nice if this could be fixed somehow

**Comment by starbelly** [comment]
I tell ya what we can do on this one... I think the "assumption" is a good convention myself, but we can provide an option that instructs rebar3_ex_doc "Don't do that".

**Comment by starbelly** [comment]
This is done, the option is `{prefix_ref_vsn_with_v, false}`
