### ISSUE TITLE
Potentially improve rebar.config UX

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [starbelly/rebar3_ex_doc#20]
I'd like

```erlang
    {extras, [
        {'README.md', #{ title => <<"Overview">> }}
    ]},
    {main, [<<"readme">>]}
```

to become

```erlang
    {extras, [
        {<<"README.md">>, #{ title => <<"Overview">> }}
        % ^a binary
    ]},
    {main, [<<"README.md">>]}
    %          ^same name as above
```

as I believe this improves UX. @starbelly, let me know and I can probably PR for this. Thanks.

**Comment by starbelly** [comment]
I'd be totally fine with this. A PR would be greatly appreciated.

**Comment by paulo-ferraz-oliveira** [comment]
I'm giving a go at this. I ended up choosing "strings" over "binaries", because:

1. we write less, this way (no `<<` or `>>`),
2. it's closer to how Elixir binaries are represented.
