### ISSUE TITLE
Update tests to include edoc opts 

### ISSUE THREAD

**Issue by starbelly** [starbelly/rebar3_ex_doc#29]
Currently there are no tests that include edoc opts. Stub config in tests should be modified to include edoc opts in some cases, especially edge cases to ensure we're doing the right thing.

**Comment by paulo-ferraz-oliveira** [comment]
You mean [these options](https://www.erlang.org/doc/man/edoc.html#run-2), right? Gimme a few examples of tests you'd like to see present and I'll try to make some happen...

**Comment by paulo-ferraz-oliveira** [comment]
Now that `ex_doc` is closer than ever to be released for Erlang/OTP doc. (already in 27.0-rc1), and the documentation system itself is changing, is this still something you think we should keep open? I'm afraid EDoc will eventually be deprecated/removed so it would be "work in vain".

**Comment by starbelly** [comment]
Agreed, this is already stale :)
