### ISSUE TITLE
ex_doc deletes all files in the doc/ directory

### ISSUE THREAD

**Issue by fredyouhanaie** [starbelly/rebar3_ex_doc#33]
I have just started trying out ex_doc alongside edoc. The first thing I noticed was that the original contents of the doc directory, in my case "overview.edoc" and ".gitignore", was cleared during the run :-(

Of course this can be prevented with the "--output" command line option, but having to type that every time is a bit tedious!

Any chances of supporting the "output" option in the rebar.config file?

I should be able to provide a PR in a week or two, unless someone is already working on this.

**Comment by starbelly** [comment]
It would be appreciated 👍

**Comment by fredyouhanaie** [comment]
fixed with PR #36
