### ISSUE TITLE
cannot override the rebar.config options via command line options

### ISSUE THREAD

**Issue by fredyouhanaie** [starbelly/rebar3_ex_doc#35]
Hi

If we have an option in the `rebar.config` file, say `{logo, "assets/logo1.png"}`, we cannot override it from the command line with
`rebar3 ex_doc --logo assets/logo2.png`.

This seems to be due to the plug-in creating the `docs.config` file from the `rebar.config` file, and passing it to the `ex_doc` command via `--config`. The latter in turn overrides the `--logo` option, which was meant to override the `rebar.config` setting :-( 

Is this the normal/expected behaviour?

**Comment by starbelly** [comment]
I would classify this as a bug. The question is whether ex_doc agrees (i.e., is the precedence normal or not).

**Comment by starbelly** [comment]
Consensus is this is unexpected behaviour in ex_doc, thus we should do a PR to it vs here. I say would work on a PR to ex_doc, but if you or someone else can get to it first, go for it! :)

**Comment by fredyouhanaie** [comment]
OK. I'll go with the consensus :)

My original thinking comes from the `ex_doc` usage text:

```
ex_doc -h
...
-c, --config        Give configuration through a file instead of a command line.
                         See "Custom config" section below for more information.
...

```
Which gives the impression that the "Custom config" override the command line option, while the command line option overrides the `mix.exs` settings.

I'll leave the PR to someone more knowledgable about Elixir :)

**Comment by starbelly** [comment]
This was fixed per https://github.com/elixir-lang/ex_doc/pull/1679 

We'll cut a new version with updated ex_doc soon.

**Comment by fredyouhanaie** [comment]
Many thanks :-)
