### ISSUE TITLE
ExDoc version

### ISSUE THREAD

**Issue by wojtekmach** [starbelly/rebar3_ex_doc#4]
New version of ExDoc was recently released but it seems rebar3_ex_doc continues to use v0.26. I think pinning to a particular version is a good call but I wonder if it can be configured somehow? Or it's cached somehow somewhere? Any advice and/or documentation on this would be very appreciated.

**Comment by starbelly** [comment]
@wojtekmach Indeed. We only used git since there wasn't a release of ex_doc that had a change I needed it in out yet. So, very happy to update :) 

I started to do that this morning, but noticed a bug in ex_doc. I'm not sure it should block us from updating though. I found that the settings menu didn't work locally.

**Comment by starbelly** [comment]
@wojtekmach It's a bug in ex_doc for both elixir and erlang projects, but it'll still work online. We can go ahead and do a patch release and then another once the bug gets fixed in ex_doc.

**Comment by starbelly** [comment]
@wojtekmach I published 0.2.5 but reverted, that settings menu bug reared its head on hexdocs.pm as well. 

```
Uncaught TypeError: Object(...)(...) is null
```

**Comment by starbelly** [comment]
@wojtekmach I also failed to answer your question. Do you mean how can you as a user of the plugin decide what version of ex_doc it should use? 

That's tough, as the escript ships with it, we might be able to let you configure the ex_doc path though. Thoughts?

**Comment by wojtekmach** [comment]
Ah, it makes sense the package ships with ExDoc escript.

I think ability to use your own ExDoc over the one shipped with the package would be very helpful. If only to exactly investigate ExDoc bugs! Path configuration would be one way to do it. Another would be somehow picking `ex_doc` that is in your `$PATH`. Not sure which approach is simpler, I guess specifying the path is potentially more flexible.

**Comment by starbelly** [comment]
Let's make it so! I'll get something together soon and get you in on the review. 

rebar3_ex_doc 0.2.5 was re-shipped : https://hexdocs.pm/rebar3_ex_doc/
