### ISSUE TITLE
Trigger issue when new ex_doc releases have been released.

### ISSUE THREAD

**Issue by starbelly** [starbelly/rebar3_ex_doc#57]
This should be doable with github actions I believe. It would make keeping up to date easier.

**Comment by MarkoMin** [comment]
Definitely agree with this one. Which option would be more convenient:

1. Create a cron action that checks like every week/month for a new version of ex_doc
2. In ex_doc repostirory, create a on_release action that uses checkout action to create an issue in rebar3_ex_doc repo.
