### ISSUE TITLE
Navigation tree and `docs_config.js` missing when generating doc

### ISSUE THREAD

**Issue by kianmeng** [starbelly/rebar3_ex_doc#62]
```
$ asdf current
elixir          1.13.4          /tmp/rebar3_ex_doc/.tool-versions
erlang          24.3.4.3        /tmp/rebar3_ex_doc/.tool-versions
```

![Screenshot from 2023-08-12 12-13-47](https://github.com/starbelly/rebar3_ex_doc/assets/134518/c80a57f8-4ca2-4e74-adda-cdcde7dd90cb)

**Comment by kianmeng** [comment]
I've tried with `ex_doc`, saw the same missing file error, but the navigation tree did show up by default, the `PAGES` tab was selected.

![image](https://github.com/starbelly/rebar3_ex_doc/assets/134518/b177bb69-ca96-41b0-b028-381e4e8d6be5)

Perhaps this is an issue with `ex_doc`, should we report upstream?

**Comment by paulo-ferraz-oliveira** [comment]
@kianmeng, @starbelly, was this eventually reported upstream? I can replicate the "missing file" issue, but I'm not sure what that file is for, since all documentation is generated and navigation seems Ok.

**Comment by kianmeng** [comment]
@paulo-ferraz-oliveira I have submitted the issue upstream, https://github.com/elixir-lang/ex_doc/issues/1789. Thanks for the reminder.

**Comment by josevalim** [comment]
Yes, the file is never there by default. It is added by hex.pm with metadata about the docs, but otherwise, you can safely ignore it.

**Comment by paulo-ferraz-oliveira** [comment]
@kianmeng, given @josevalim's input, I'm not sure there's much we can do. What's intriguing, though, is that you seem to present a situation where the docs were not generated (this I couldn't replicate, even with the missing file - so probably not related (?)). @starbelly, thoughts?

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira  I agree with @josevalim, it's non-critical and doesn't impact experience locally AFAIK. It would only be noticed by inspecting the browser console, once again, locally. 

I'm going to close this, yet please feel free to open if you feel differently.

**Comment by paulo-ferraz-oliveira** [comment]
I was able to replicate this locally when using `_checkouts` on a `rebar3` project. Out of scope for fixing, but a reference nonetheless.
