### ISSUE TITLE
`with_mermaid` embedded after `before_closing_body_tag`

### ISSUE THREAD

**Issue by MarkoMin** [starbelly/rebar3_ex_doc#63]
I have I use case where I want to use mermaid to render diagrams in docs, but I want to manipulate `<svg>` elements afterwards with custom javascript. When I embed mermaid script manually in `before_closing_body_tag` it works, but when I use `with_mermaid` option, graphs are renedered, but not customized via JS. Can mermaid script be executed b4 `before_closing_body_tag`?

I didn't dig into source, but I could come with PR if the solution is wanted.

**Comment by starbelly** [comment]
This was fixed up in #59 if I understand you problem correctly. Are you using the latest version 0.2.20?

**Comment by MarkoMin** [comment]
No, that issue just made the solution complete. However, imagine if you want to set all diagrams to be full-screen on click. Then, you firstly need to render them (embedded script via `with_mermaid`) and than you execute `for` loop over `<svg>` elements in `before_closing_body_tag`. However, ATM `before_closing_body_tag` gets executed b4 mermaid scripts so it has no effect because diagrams are not rendered yet.

**Comment by starbelly** [comment]
@MarkoMin  I see. A PR is quite welcome.
