### ISSUE TITLE
The example link on HexDocs appears to be broken.

### ISSUE THREAD

**Issue by IciaCarroBarallobre** [starbelly/rebar3_ex_doc#76]
![image](https://github.com/starbelly/rebar3_ex_doc/assets/47258107/3dfc51c1-3bb4-403d-b511-da61d4e51849)

![image](https://github.com/starbelly/rebar3_ex_doc/assets/47258107/1fa891a0-6fba-4b88-8902-5fccf40b4e58)

I'm sorry to bother you if you were already aware of this issue.

**Comment by starbelly** [comment]
No bother :) 

We should make the link explicitly link to github. Right now it is implicit, which is the problem.

**Comment by starbelly** [comment]
Note : We're going to be moving this repository to jelly-beam org soon, will wait to fix this up after such.
